
import { TourType, Tour, Booking, VerificationStatus } from './types';

export const APP_NAME = "Community Tours and Travels";

export const NEPAL_LOCATIONS = [
  "Kathmandu",
  "Pokhara",
  "Chitwan",
  "Lumbini",
  "Mustang",
  "Nagarkot",
  "Lukla (EBC)",
  "Biratnagar"
];

export const MOCK_TOURS: Tour[] = [
  {
    id: 't1',
    ownerId: 'o1',
    name: 'Annapurna Base Camp Trek',
    type: TourType.ADVENTURE_TREK,
    pricePerPerson: 25000,
    location: 'Pokhara',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    available: true,
    verificationStatus: VerificationStatus.VERIFIED,
    features: ['Expert Guide', 'Porter Service', 'ACAP Permits', 'Teahouse Stays', 'All Meals'],
    description: '**A legendary trek** through the heart of the Annapurna Sanctuary. Experience breathtaking views of Annapurna I, Hiunchuli, and Machapuchare.\n- **Expert Mountain Guides**\n- ACAP Permits Included\n- Teahouse accommodations throughout',
    duration: 12,
    maxGroupSize: 12,
    difficulty: 'Challenging',
  },
  {
    id: 't2',
    ownerId: 'o1',
    name: 'Chitwan Wildlife Safari',
    type: TourType.WILDLIFE_SAFARI,
    pricePerPerson: 12000,
    location: 'Chitwan',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=800',
    available: true,
    verificationStatus: VerificationStatus.VERIFIED,
    features: ['Jungle Jeep Safari', 'Elephant Bathing', 'Bird Watching', 'Canoe Ride', 'Resort Stay'],
    description: 'Explore the *UNESCO World Heritage* Chitwan National Park. Spot rhinos, tigers, and exotic birds in their natural habitat.\n- **Jeep & Walking Safaris**\n- Tharu Cultural Show\n- All Meals & Transfers Included',
    duration: 3,
    maxGroupSize: 8,
    difficulty: 'Easy',
  },
  {
    id: 't3',
    ownerId: 'o2',
    name: 'Kathmandu Cultural Heritage Tour',
    type: TourType.CULTURAL_TOUR,
    pricePerPerson: 8500,
    location: 'Kathmandu',
    image: 'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?auto=format&fit=crop&q=80&w=800',
    available: true,
    verificationStatus: VerificationStatus.VERIFIED,
    features: ['7 UNESCO Sites', 'Expert Guide', 'Private Transfers', 'Lunch Included', 'Museum Entry'],
    description: 'Discover the **7 UNESCO World Heritage Sites** of the Kathmandu Valley in this immersive cultural experience.\n- Pashupatinath Temple, Boudhanath Stupa\n- Patan & Bhaktapur Durbar Squares\n- **Traditional Newari Cuisine**',
    duration: 2,
    maxGroupSize: 15,
    difficulty: 'Easy',
  },
  {
    id: 't4',
    ownerId: 'o3',
    name: 'Everest Base Camp Expedition',
    type: TourType.MOUNTAIN_EXPEDITION,
    pricePerPerson: 85000,
    location: 'Lukla (EBC)',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&q=80&w=800',
    available: false,
    verificationStatus: VerificationStatus.VERIFIED,
    features: ['Lukla Flight', 'All Permits', 'Sherpa Guide', 'Teahouse Stays', 'Emergency Evacuation'],
    description: 'The ultimate **Himalayan bucket-list experience**. Trek to the foot of the world\'s highest mountain through Sherpa villages and dramatic landscapes.\n- Sagarmatha National Park Permits\n- **Experienced Sherpa Guides**\n- Oxygen & Medical Support',
    duration: 16,
    maxGroupSize: 8,
    difficulty: 'Extreme',
  },
  {
    id: 't5',
    ownerId: 'o2',
    name: 'Lumbini Pilgrimage & Peace Tour',
    type: TourType.PILGRIMAGE,
    pricePerPerson: 9500,
    location: 'Lumbini',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&q=80&w=800',
    available: true,
    verificationStatus: VerificationStatus.PENDING,
    features: ['Maya Devi Temple', 'Monastic Zone', 'World Peace Pagoda', 'Expert Guide', 'Transfers'],
    description: 'Journey to the **birthplace of Lord Buddha** in this peaceful spiritual tour through Lumbini\'s sacred grounds.\n- Maya Devi Temple Visit\n- International Buddhist Monasteries\n- **Guided Meditation Sessions**',
    duration: 3,
    maxGroupSize: 20,
    difficulty: 'Easy',
  }
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    tourId: 't1',
    customerId: 'c1',
    startDate: '2026-04-15',
    endDate: '2026-04-27',
    numPeople: 2,
    totalPrice: 50000,
    status: 'CONFIRMED',
    destination: 'Annapurna Sanctuary',
  },
  {
    id: 'b2',
    tourId: 't3',
    customerId: 'c1',
    startDate: '2026-05-05',
    endDate: '2026-05-07',
    numPeople: 3,
    totalPrice: 25500,
    status: 'PENDING',
    destination: 'Kathmandu Valley',
  }
];
